Add: Support for 1.20
WesJD/AnvilGUI pull request #267
Opened 2023-06-07 17:55 UTC by spnda

This should work, but I didn't and can't test it thoroughly.

2023-06-07 18:15 UTC, Sytm requested changes
I was also on it and produced the same code and were able to confirm that this works.

But you forgot to add this new subproject to api/pom.xml as a dependency

2023-06-07 18:22 UTC, Kimo-boop commented
lol

2023-06-08 12:08 UTC, Sytm approved these changes

2023-06-08 23:51 UTC, JamesPeters98 commented
I've also built locally and this works fine with my plugin for 1.20 too. Can we get this merged and released @WesJD ?

2023-06-09 00:11 UTC, merged